db.pool.init_size=5
db.pool.min_size=5
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=AURORA_FIX}
db.username=${DB_USERNAME:sa}
db.password=${DB_PASSWORD:change-me}

db.url2=jdbc:sqlserver://192.168.1.102:1433;databaseName=AURORA
hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
hibernate.showSql=false
hibernate.formatSql=false
hibernate.hbm2ddl=false