spring:
  application:
    name: bank-core
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:h2:mem:bank_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /bank-core

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.bank: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

